spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongoadmin
      password: secret
      database: dc-transactions
      authentication-database: admin

data:
  transactions:
    path: pathToTransactionFile
  feeWages:
    path: pathToFeeWagesFile

auth:
  username: someuser
  password: xyz